# Generated by Django 4.2.5 on 2023-10-08 21:43

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('md_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdpages',
            name='body',
            field=wagtailmarkdown.fields.MarkdownField(blank=True),
        ),
    ]
