# Generated by Django 4.2.4 on 2023-09-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_caption_blogpagegalleryimage_answer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPageGalleryImage',
            new_name='Questions',
        ),
    ]
