# Generated by Django 4.2.4 on 2023-09-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_blogpagegalleryimage_questions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='MultipleChoice',
        ),
    ]
