# Generated by Django 4.2.4 on 2023-09-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_questions_multiplechoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoice',
            name='optionA',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='optionB',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='optionC',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='optionD',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
