# Generated by Django 4.2.4 on 2023-09-05 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clozequestion',
            options={'verbose_name_plural': 'ClozeQuestion'},
        ),
    ]
