# Generated by Django 4.2.4 on 2023-09-06 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_clozequestion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multiplechoice',
            options={'verbose_name_plural': 'MultipleChoice'},
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
