# Generated by Django 4.2.4 on 2023-09-06 07:09

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_remove_multiplechoice_optiona_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoice',
            name='option',
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock())], default='null', use_json_field=True),
            preserve_default=False,
        ),
    ]
