# Generated by Django 4.2.4 on 2023-09-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_multiplechoice_option_multiplechoice_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoice',
            name='body',
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='optionA',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='optionB',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='optionC',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='optionD',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
