# Generated by Django 4.2.4 on 2023-09-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_remove_multiplechoice_intro_multiplechoice_shortcut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoice',
            name='shortcut',
            field=models.CharField(max_length=250),
        ),
    ]
