# Generated by Django 4.2.4 on 2023-09-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_multiplechoice_shortcut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoice',
            name='answer',
            field=models.CharField(choices=[(models.CharField(blank=True, max_length=250), 'A'), (models.CharField(blank=True, max_length=250), 'B'), (models.CharField(blank=True, max_length=250), 'C'), (models.CharField(blank=True, max_length=250), 'D')], max_length=10),
        ),
    ]
