# Generated by Django 4.2.4 on 2023-09-06 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_multiplechoice_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplechoice',
            old_name='optionA',
            new_name='option_a',
        ),
        migrations.RenameField(
            model_name='multiplechoice',
            old_name='optionB',
            new_name='option_b',
        ),
        migrations.RenameField(
            model_name='multiplechoice',
            old_name='optionC',
            new_name='option_c',
        ),
        migrations.RenameField(
            model_name='multiplechoice',
            old_name='optionD',
            new_name='option_d',
        ),
    ]
