# Generated by Django 4.2.4 on 2023-09-06 08:38

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_rename_optiona_multiplechoice_option_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoice',
            name='question',
            field=wagtail.fields.RichTextField(),
        ),
    ]
