# Generated by Django 4.2.4 on 2023-09-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_alter_multiplechoice_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoice',
            name='answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10),
        ),
    ]
