# Generated by Django 4.2.4 on 2023-09-12 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_multiple_clozequestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiple',
            name='page',
        ),
        migrations.DeleteModel(
            name='ClozeQuestion',
        ),
        migrations.DeleteModel(
            name='Multiple',
        ),
    ]
