# Generated by Django 4.2.4 on 2023-09-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_multiplechoice_clozequestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoice',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='multiplechoice',
            name='live_revision',
        ),
        migrations.RemoveField(
            model_name='multiplechoice',
            name='page',
        ),
        migrations.DeleteModel(
            name='ClozeQuestion',
        ),
        migrations.DeleteModel(
            name='MultipleChoice',
        ),
    ]
