# Generated by Django 4.2.4 on 2023-09-12 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('pages', '0028_multiplechoice_clozequestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clozequestion',
            name='page',
        ),
        migrations.RemoveField(
            model_name='multiplechoice',
            name='expire_at',
        ),
        migrations.RemoveField(
            model_name='multiplechoice',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='multiplechoice',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='multiplechoice',
            name='go_live_at',
        ),
        migrations.RemoveField(
            model_name='multiplechoice',
            name='has_unpublished_changes',
        ),
        migrations.RemoveField(
            model_name='multiplechoice',
            name='id',
        ),
        migrations.RemoveField(
            model_name='multiplechoice',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='multiplechoice',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='multiplechoice',
            name='live',
        ),
        migrations.RemoveField(
            model_name='multiplechoice',
            name='live_revision',
        ),
        migrations.RemoveField(
            model_name='multiplechoice',
            name='page',
        ),
        migrations.AddField(
            model_name='multiplechoice',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default=5, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page'),
            preserve_default=False,
        ),
    ]
