# Generated by Django 4.2.4 on 2023-09-14 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_remove_multiplechoice_page_ptr_clozequestion_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoice',
            name='page',
        ),
        migrations.DeleteModel(
            name='ClozeQuestion',
        ),
        migrations.DeleteModel(
            name='MultipleChoice',
        ),
    ]
