# Generated by Django 4.2.4 on 2023-09-12 08:56

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClozeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('question', wagtail.fields.RichTextField(blank=True)),
                ('answer', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name_plural': 'ClozeQuestion',
            },
        ),
        migrations.CreateModel(
            name='Multiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('shortcut', models.CharField(max_length=250)),
                ('question', wagtail.fields.RichTextField()),
                ('option_a', models.CharField(blank=True, max_length=250)),
                ('option_b', models.CharField(blank=True, max_length=250)),
                ('option_c', models.CharField(blank=True, max_length=250)),
                ('option_d', models.CharField(blank=True, max_length=250)),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'MultipleChoice',
            },
        ),
    ]
