# Generated by Django 4.2.4 on 2023-09-12 13:01

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('pages', '0027_remove_multiplechoice_latest_revision_and_more'),
        ('question', '0002_remove_multiple_sort_order_multiple_expire_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('shortcut', models.CharField(max_length=250)),
                ('question', wagtail.fields.RichTextField()),
                ('option_a', models.CharField(blank=True, max_length=250)),
                ('option_b', models.CharField(blank=True, max_length=250)),
                ('option_c', models.CharField(blank=True, max_length=250)),
                ('option_d', models.CharField(blank=True, max_length=250)),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10)),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='multipleChoice', to='pages.pages')),
            ],
            options={
                'verbose_name_plural': 'MultipleChoice',
            },
        ),
        migrations.AddField(
            model_name='clozequestion',
            name='page',
            field=modelcluster.fields.ParentalKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='clozeQuestion', to='pages.pages'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Multiple',
        ),
    ]
