# Generated by Django 4.2.4 on 2023-08-30 08:25

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_author_blogpage_authors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtailmarkdown.fields.MarkdownField(),
        ),
    ]
