# Generated by Django 4.2.4 on 2023-08-30 09:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_blogpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpagegalleryimage",
            name="image",
        ),
        migrations.RemoveField(
            model_name="blogpagegalleryimage",
            name="page",
        ),
        migrations.RemoveField(
            model_name="blogpage",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="blogpage",
            name="date",
        ),
        migrations.RemoveField(
            model_name="blogpage",
            name="intro",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="BlogPageGalleryImage",
        ),
    ]
