# Generated by Django 4.2.4 on 2023-08-31 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_remove_blogpagegalleryimage_image_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogIndexPage",
        ),
    ]
