# Generated by Django 4.2.6 on 2023-10-19 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('md_pages', '0002_alter_mdpages_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClozePublish',
            fields=[
                ('publish_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('pubished_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClozeUserChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('correct', models.BooleanField(default=False)),
                ('publish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_cloze.clozepublish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClozeQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=200)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('published', models.BooleanField(default=False)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloze_questions', to='md_pages.mdpages')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.AddField(
            model_name='clozepublish',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_cloze.clozequestion'),
        ),
    ]
