# Generated by Django 4.2.6 on 2023-10-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_cloze', '0002_clozequestion_correct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clozequestion',
            options={'verbose_name': '填空题', 'verbose_name_plural': '填空题'},
        ),
    ]
