# Generated by Django 4.2.4 on 2023-09-16 07:38

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publish',
            name='question',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish', to='polls.question'),
        ),
    ]
