# Generated by Django 4.2.4 on 2023-09-16 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_publish_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publish',
            name='are_you_sure',
        ),
    ]
