# Generated by Django 4.2.5 on 2023-09-21 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_publish_publish_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
