# Generated by Django 4.2.5 on 2023-10-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_remove_question_published_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publish',
            name='id',
        ),
        migrations.AlterField(
            model_name='publish',
            name='publish_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
