# Generated by Django 4.2.5 on 2023-10-08 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_publish_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchoice',
            old_name='publish_id',
            new_name='publish',
        ),
        migrations.RemoveField(
            model_name='userchoice',
            name='question',
        ),
    ]
