# Generated by Django 4.2.5 on 2023-10-08 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_rename_publish_id_userchoice_publish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
