# Generated by Django 4.2.5 on 2023-10-08 22:46

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('polls', '0027_remove_choice_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='page',
            field=modelcluster.fields.ParentalKey(default=21, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='wagtailcore.page'),
            preserve_default=False,
        ),
    ]
