# Generated by Django 4.2.5 on 2023-09-15 02:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_question_published_question_published_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoice',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
