# Generated by Django 4.2.4 on 2023-09-16 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_publish_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publish',
            options={},
        ),
    ]
