# Generated by Django 4.2.4 on 2023-09-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_remove_publish_are_you_sure'),
    ]

    operations = [
        migrations.AddField(
            model_name='publish',
            name='publish_id',
            field=models.IntegerField(default=0),
        ),
    ]
