# Generated by Django 4.2.5 on 2023-09-22 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_remove_question_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publish',
            name='delay_duration',
        ),
    ]
