# Generated by Django 4.2.5 on 2023-09-22 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_remove_publish_delay_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='published_end_date',
        ),
    ]
