# Generated by Django 4.2.5 on 2023-10-07 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_remove_publish_id_alter_publish_publish_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoice',
            name='publish_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.publish'),
            preserve_default=False,
        ),
    ]
