# Generated by Django 4.2.5 on 2023-10-08 23:13

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('md_pages', '0002_alter_mdpages_body'),
        ('polls', '0029_alter_question_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Choice', 'verbose_name_plural': 'Choices'},
        ),
        migrations.AlterField(
            model_name='question',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='md_pages.mdpages'),
        ),
    ]
