# Generated by Django 4.2.5 on 2023-10-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0047_alter_userchoice_choice_clozeuserchoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clozequestion',
            name='page',
        ),
        migrations.RemoveField(
            model_name='clozeuserchoice',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='clozeuserchoice',
            name='user',
        ),
        migrations.AlterField(
            model_name='userchoice',
            name='choice',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='ClozePublish',
        ),
        migrations.DeleteModel(
            name='ClozeQuestion',
        ),
        migrations.DeleteModel(
            name='ClozeUserChoice',
        ),
    ]
