# Generated by Django 4.2.5 on 2023-10-12 05:29

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0048_remove_clozequestion_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
