# Generated by Django 4.2.5 on 2023-10-12 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0049_question_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoice',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.choice'),
        ),
    ]
