# Generated by Django 4.2.6 on 2023-10-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0050_alter_userchoice_choice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '选择题', 'verbose_name_plural': '选择题'},
        ),
    ]
