# Generated by Django 4.2.6 on 2023-11-14 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0051_alter_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_text'], 'verbose_name': '选择题', 'verbose_name_plural': '选择题'},
        ),
    ]
