# Generated by Django 4.2.4 on 2023-09-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookhome",
            name="author",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
