# Generated by Django 4.2.6 on 2023-11-14 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('book', '0005_bookhome_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookHome',
            new_name='Book',
        ),
    ]
